### ISSUE TITLE
ci windows build fails: openssl needs other version of perl

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/napi-jsonrpc#4]
```
******************************************************************************
  This perl implementation doesn't produce Windows like paths (with backward
  slash directory separators).  Please use an implementation that matches your
  building platform.

  This Perl version: 5.36.0 for x86_64-msys-thread-multi
  ******************************************************************************
[224](https://github.com/deltachat/napi-jsonrpc/actions/runs/3303479822/jobs/5451449254#step:12:225)
  thread 'main' panicked at '
[225](https://github.com/deltachat/napi-jsonrpc/actions/runs/3303479822/jobs/5451449254#step:12:226)
```

https://github.com/deltachat/napi-jsonrpc/actions/runs/3303479822/jobs/5451449254

Internet says we need a different version of perl, but I couldn't find out which one exactly nor how to use/install it.

**Comment by missytake** [comment]
This stackoverflow answer recommends using a certain github action to pin a perl version: https://stackoverflow.com/a/72370624/13505504

I think we need to explicitly use "strawberry perl", a perl version for windows. see: https://github.com/telegramdesktop/tdesktop/issues/10225

**Comment by missytake** [comment]
```
      - name: Setup perl
        if: {{ matrix.settings.host == windows }}
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl-version }}
          distribution: strawberry
```

**Comment by missytake** [comment]
Somehow the CI isn't running right now: https://github.com/deltachat/napi-jsonrpc/actions/runs/3314510505

Merging it didn't solve that. But it accidentally closed this issue, so I'm reopening it.

**Comment by Simon-Laux** [comment]
I found our issue: https://github.com/alexcrichton/openssl-src-rs/issues/45
```yml
  - name: Use strawberry perl
      if: startsWith(matrix.os, 'windows')
      run: echo OPENSSL_SRC_PERL=C:/Strawberry/perl/bin/perl >> $GITHUB_ENV
```
